travis:
  secure:
    BINSTAR_TOKEN: PrUNxoE8qPFpq28DdwLK0J9iHIyiAslJwzGgztJs19JEHdg9IQXUIxXCZVTvAp3Z5/2+e+PBUcS/a0P37YUNBIf25hO4PmSFWU4RR/LN0/NCMQSxeRAVMPThiyC9z0k/aRf5B1vRMRdptc44B3TFPW5kXl0w6ZutBMERB7cwD6qjXmOrYYoUMVZquF7RXBVvU2fuTdjfZ83E2GyzscChEiGkpgIcdsRUg/paWIjuCiy+94JbeX+3GhsRQKDq7ggwDl26UiM+DFBzrLSaKd+3/0xoNYrOj+DWfH6+1iAUUx6oBCD9BHwl+tP0/OmqA4dlVFFMJl8DRop5LAPLHIRH+6pshWWzmPqMCUtKCs3uD1DXlvF5zQ61XhF7M7n+O5TSFV2XAQ4AsrpFU7FNU7znAxtDUXPE8iX9LM9+1RwCav6/bcNER/pFtiRdhU2U6V5sPRtepbbbLhqESkKe4lOf7kYBVl/cfnnh9gyrxLJGa6S7ILBdw5tG/HIFj0jzY2Ik9hIiu+w7HY8tOaIiPt3+3a6E+od8HNmQ7IHG1uFgkuNV4Bi9TP8BHMFqPAQo/17OXYFQes8B59e8DSb5sAEZddnYQK09i+AwrSI1Jtp9F1fg+XBVPBqNCDmk5IyGacywTuqD1/EUxVv+6mP2lBPJiVQ+Ul5et9CKIxjGWTpEdnA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
